### ISSUE TITLE
packages.baidu.com 网速问题

### ISSUE THREAD

**Issue by Explorer1092** [baidu-security/app-env-docker#35]
在家里编译软件时，网速不错。但是在阿里云上编译，感觉网速低于本地。是有什么限速策略么？

![image](https://user-images.githubusercontent.com/32663226/66887064-4b976e80-f00c-11e9-99d1-b7a6d79c8789.png)

**Comment by Explorer1092** [comment]
国外下载文件速度很慢，建议套一层cdn。

**Comment by CaledoniaProject** [comment]
package 出口是联通的，速度我们控制不了，如果不够快可能是你的VPS带宽问题吧。CDN 这个就不用想了，package 只是临时用来下载软件的，并非公司业务。
