### ISSUE TITLE
socks5部署问题

### ISSUE THREAD

**Issue by Exi1Sh0w** [baidu-security/app-env-docker#39]
对docker还不是很懂，在谷歌许久后还是没有找到答案。
“ExecStart=/usr/bin/dockerd -H fd:// -H tcp://0.0.0.0:2375”
根据文档使用这条命令报错，提示“-H: command not found”...
还请麻烦讲解一下，谢谢了

**Comment by a0xpg** [comment]
编辑文件：
vim /lib/systemd/system/docker.service
ExecStart=/usr/bin/dockerd -H fd:// -H tcp://0.0.0.0:2375

重新启动docker服务

**Comment by CaledoniaProject** [comment]
上面的回答是正确的，我把ISSUE关掉吧
